import OmegaY.Official.Build
import OmegaY.Official.Check
import OmegaY.Official.Reserve
import OmegaY.Official.ReserveCheck
import OmegaY.Official.Descent
import OmegaY.Official.Dimension
import OmegaY.Official.Reconstruction
import OmegaY.Official.Classification.Bridge
import OmegaY.Official.Classification.Proofs.ControlDominates
import OmegaY.Official.Recon.FirstEmit
import OmegaY.Official.Recon.ChainSplit
import OmegaY.Official.Recon.RowLawColumn
import OmegaY.Official.Recon.ParentBelow
import OmegaY.Official.Classification.Proofs.ChainCorrLegLeft
import OmegaY.Official.Classification.Proofs.ChainCorrLegLeftItems
import OmegaY.Official.Classification.Proofs.ChainCorrLegLeftLookup
import OmegaY.Official.Classification.Proofs.ChainCorrLegLeftMain
import OmegaY.Official.Classification.Proofs.ChainCorrLegLeftRoutes
import OmegaY.Official.Classification.Proofs.ChainCorrLegLeftJump
import OmegaY.Official.Recon.JumpLawLowerLeft
import OmegaY.Official.Recon.ParentBelowLowerProfile
import OmegaY.Official.Recon.ParentBelowLowerCore
import OmegaY.Official.Recon.ParentBelowLowerCols
import OmegaY.Official.Recon.ParentBelowLowerMain
import OmegaY.Official.Recon.ParentBelowLowerLeg
import OmegaY.Official.Recon.CrossKinds
import OmegaY.Official.Recon.JumpLawSeam
import OmegaY.Official.Classification.Proofs.ChainCorrCopyMono
import OmegaY.Official.Classification.Proofs.ChainCorrStartRoot
import OmegaY.Official.Classification.Proofs.ChainCorrStartLegJump
import OmegaY.Official.Classification.Proofs.ChainCorrStepInner
import OmegaY.Official.Classification.Proofs.StepInnerCleanLift
import OmegaY.Official.Classification.Proofs.StepInnerCleanNext
import OmegaY.Official.Classification.Proofs.StepInnerCleanParent
import OmegaY.Official.Classification.Proofs.StepInnerCleanLookup
import OmegaY.Official.Classification.Proofs.StepInnerCleanBoundary
import OmegaY.Official.Classification.Proofs.CopyShape
import OmegaY.Official.Classification.Proofs.CopyShapeChildren
import OmegaY.Official.Classification.Proofs.CopyShapeItems
import OmegaY.Official.Classification.Proofs.CopyShapeMD
import OmegaY.Official.Classification.Proofs.CopyShapeMaps
import OmegaY.Official.Classification.Proofs.CopyShapeRun
import OmegaY.Official.Classification.Proofs.CutPartsGen
import OmegaY.Official.Classification.Proofs.CutPartsPaRow
import OmegaY.Official.Classification.Proofs.CutPartsStart
import OmegaY.Official.Classification.Proofs.CutPartsStep
import OmegaY.Official.Classification.Proofs.CutPartsTop
import OmegaY.Official.Classification.Proofs.LegBelowTopFalse
import OmegaY.Official.Classification.Proofs.LegRowMatchBoundary
import OmegaY.Official.Classification.Proofs.LegRowMatchLower
import OmegaY.Official.Classification.Proofs.LegRowMatchTop
import OmegaY.Official.Classification.Proofs.StartRootParts
import OmegaY.Official.Classification.Proofs.StartRootPartsB0
import OmegaY.Official.Classification.Proofs.StartRootPartsBase
import OmegaY.Official.Classification.Proofs.StartRootPartsBlock0
import OmegaY.Official.Classification.Proofs.StartRootPartsBoundary
import OmegaY.Official.Classification.Proofs.StartRootPartsCols
import OmegaY.Official.Classification.Proofs.StartRootPartsCutTop
import OmegaY.Official.Classification.Proofs.StartRootPartsOrigin
import OmegaY.Official.Classification.Proofs.StartRootPartsOriginLower
import OmegaY.Official.Classification.Proofs.StepInnerLookupBump
import OmegaY.Official.Classification.Proofs.StepInnerLookupLeg
import OmegaY.Official.Recon.CrossPlainBlock0
import OmegaY.Official.Recon.CrossPlainNormal
import OmegaY.Official.Recon.CrossUpper
import OmegaY.Official.Recon.CrossUpperColumns
import OmegaY.Official.Recon.CrossUpperCopy
import OmegaY.Official.Recon.CrossUpperNormal
import OmegaY.Official.Recon.CrossUpperSeam
import OmegaY.Official.Recon.CutPredBase
import OmegaY.Official.Recon.CutPredBoundary
import OmegaY.Official.Recon.CutPredFloor
import OmegaY.Official.Recon.CutPredGap
import OmegaY.Official.Recon.CutPredItems
import OmegaY.Official.Recon.CutPredLift
import OmegaY.Official.Recon.CutPredMain
import OmegaY.Official.Recon.CutPredShape
import OmegaY.Official.Recon.JumpLawLower
import OmegaY.Official.Recon.JumpLawLowerChildren
import OmegaY.Official.Recon.JumpLawLowerLeg
import OmegaY.Official.Recon.JumpLawLowerSplit
import OmegaY.Official.Recon.JumpLawLowerTree
import OmegaY.Official.Classification.Proofs.KeyRegions
import OmegaY.Official.Classification.Proofs.ChainsCanonParent
import OmegaY.Official.Classification.Proofs.ChainCorrRegions

/-! The official omega-Y expansion (notes/03-official-rule.md): the executable
definition `OmegaY.Official.expand` and its fixtures against the official
program; the leg atoms and the splice classification (notes/04-official-design.md)
and their check on the same fixtures; the well-foundedness of the official
expansion from the degree bound and the atom classification
(`Reconstruction.wellFounded_of_parts`); the dimension bound (`Dimension`). -/
