/-
Adapted from Phyrion, omega-Y-Well-Ordering-Lean, OmegaY/Expansion/ActualFillEdgeKeys.lean,
revision 33c16a8ce8f7e01bb3794881f3ff9109474beaed (Apache-2.0).
Changes: none besides this header.
-/
import OmegaY.Geometry.FillEdgeKeys
import OmegaY.Expansion.ActualCopiedNodeOrigin
import OmegaY.Expansion.ActualCanonicalReconstruction

/-!
# Strict key control of actual reference-gap edges

The copied-node packet is obtained from the unchanged real copy loops and
the final pop. Its reference-gap branch supplies an actual fill execution,
membership, and the shape preserved by finish. These expose actual parent
and high-reference reads in the final mountain. No output degree bound,
root-vector inequality, or output normality is supplied by the caller of
the final theorem.

Here a fill edge means that its *upper* node was generated by fill. The
edge from the top gap node to the first contour node is an effective edge,
and is intentionally not classified as a fill edge by this theorem.
-/

namespace OmegaY.Expansion

open Canonical Geometry Frame

universe u

/-- Actual fill membership identifies the stored parent and its interval
upper, as well as the selected high reference in the same existing column.
Every array default disappears behind a proved successful actual read. -/
theorem CopiedNodeOrigin.reference_gap_edge_rows
    {front : List Nat} {last : Nat} {p : Preparation front last} {result : Mountain}
    (edge : RealStoredEdge (Frame.ofMountain result))
    (packet : CopiedNodeOrigin p result edge.upper)
    {marker : Ref} (hm : marker ∈ packet.data.bucket) {gap : List Cell} {original : Cell}
    (hFill : fill packet.before ⟨packet.sourceColumn, marker.index + 1⟩
      (packet.block * (p.reduced.size - 1 - p.root.column))
      (packet.data.marker_data marker hm).current.row
      (packet.data.marker_data marker hm).targetCell.row = .ok gap)
    (hMember : original ∈ gap)
    (hShape : SameShape original ((Frame.ofMountain result).cell edge.upper)) :
    ∃ (reference : (Frame.ofMountain result).Node) (middle : Row),
      Frame.ref reference =
        ⟨(packet.data.marker_data marker hm).sourceParent.column +
          packet.block * (p.reduced.size - 1 - p.root.column),
          (packet.data.marker_data marker hm).targetIndex⟩ ∧
      (Frame.ofMountain result).cell reference = (packet.data.marker_data marker hm).targetCell ∧
      edge.parent.1 = reference.1 ∧
      (Frame.ofMountain result).height edge.parent < middle ∧
      middle ≤ (Frame.ofMountain result).height reference ∧
      (Frame.ofMountain result).height edge.upper ∈
        Row.fillLadder ((Frame.ofMountain result).height edge.parent) middle := by
  let d := packet.data
  let md := d.marker_data marker hm
  let shift := packet.block * (p.reduced.size - 1 - p.root.column)
  have hBefore : PreservesColumns packet.before result :=
    (PreservesColumns.push packet.before packet.column).trans packet.preserved
  obtain ⟨hp, hParentNodes⟩ := Array.getElem?_eq_some_iff.mp md.parent_nodes
  have hParentValid : ColumnValid packet.before (md.sourceParent.column + shift) md.parentNodes :=
    hParentNodes ▸ d.ambient_valid _ hp
  have hStrict := fillRowsStrict_of_columnValid hParentValid
  have hUpperRead : lookup packet.before ⟨packet.sourceColumn, marker.index + 1⟩ = .ok md.upper :=
    lookup_ok_iff.mpr ⟨d.sources, d.source_column, md.upper_at⟩
  have hLeftward := (d.source_valid.stored_valid _ _ _ md.upper_at md.upper_left).1
  have hExact := fill_eq_cells hUpperRead md.upper_left md.parent_nodes hStrict md.target_at
    le_rfl (Nat.add_lt_add_right hLeftward shift) (low := md.current.row)
  have hGap : gap = fillCells md.parentNodes (md.sourceParent.column + shift)
      md.current.row md.targetCell.row := Except.ok.inj (hFill.symm.trans hExact)
  have hActualMember : original ∈ fillCells md.parentNodes (md.sourceParent.column + shift)
      md.current.row md.targetCell.row := hGap ▸ hMember
  obtain ⟨parentIndex, parent, parentUpper, hParent, _, _, _, hParentRow, hUpperCap,
    hRung, _, hLeft⟩ := mem_fillCells hStrict md.target_at le_rfl hActualMember
  have hNodesFinal : result[md.sourceParent.column + shift]? = some md.parentNodes :=
    hBefore.column_read md.parent_nodes
  have hParentRead : Canonical.cellAt result ⟨md.sourceParent.column + shift, parentIndex⟩ = .ok parent :=
    cellAt_ok_iff.mpr ⟨md.parentNodes, hNodesFinal, hParent⟩
  have hTargetRead : Canonical.cellAt result ⟨md.sourceParent.column + shift, md.targetIndex⟩ =
      .ok md.targetCell := cellAt_ok_iff.mpr ⟨md.parentNodes, hNodesFinal, md.target_at⟩
  obtain ⟨actualUpper, hActualUpper, hStored⟩ := rawParent_spec edge.parent_eq
  have hUpperEq : actualUpper = edge.upper :=
    Option.some.inj (hActualUpper.symm.trans edge.upper_eq)
  subst actualUpper
  have hParentRef : Frame.ref edge.parent = ⟨md.sourceParent.column + shift, parentIndex⟩ :=
    Option.some.inj (hStored.symm.trans (hShape.2.symm.trans hLeft))
  have hParentRead' : Canonical.cellAt result (Frame.ref edge.parent) = .ok parent := by
    rw [hParentRef]
    exact hParentRead
  have hParentCell : (Frame.ofMountain result).cell edge.parent = parent :=
    Except.ok.inj ((Canonical.cellAt_of_frame_node result edge.parent).symm.trans hParentRead')
  obtain ⟨reference, hReferenceRef, hReferenceCell⟩ := Canonical.frame_node_of_cellAt hTargetRead
  have hColumn : edge.parent.1 = reference.1 := Fin.ext
    ((congrArg Ref.column hParentRef).trans (congrArg Ref.column hReferenceRef).symm)
  refine ⟨reference, parentUpper.row, hReferenceRef, hReferenceCell, hColumn, ?_, ?_, ?_⟩
  · simpa only [Frame.height, hParentCell] using hParentRow
  · simpa only [Frame.height, hReferenceCell] using hUpperCap
  · change ((Frame.ofMountain result).cell edge.upper).row ∈
      Row.fillLadder ((Frame.ofMountain result).cell edge.parent).row parentUpper.row
    rw [← hShape.1, hParentCell]
    exact hRung

/-- All actual reference-fill upper edges have degree strictly below the
parent-to-reference jump and key strictly below that reference's complete
degree-zero root key. Normality comes from the completed executable run. -/
theorem CopiedNodeOrigin.reference_gap_edge_key_bound
    {front : List Nat} {last : Nat} {p : Preparation front last} {result : Mountain}
    (hLegal : Legal (front ++ [last])) {copies : Nat}
    (hRun : expandDiagram (front ++ [last]) copies = .ok result)
    (edge : RealStoredEdge (Frame.ofMountain result))
    (packet : CopiedNodeOrigin p result edge.upper)
    {marker : Ref} (hm : marker ∈ packet.data.bucket) {gap : List Cell} {original : Cell}
    (hFill : fill packet.before ⟨packet.sourceColumn, marker.index + 1⟩
      (packet.block * (p.reduced.size - 1 - p.root.column))
      (packet.data.marker_data marker hm).current.row
      (packet.data.marker_data marker hm).targetCell.row = .ok gap)
    (hMember : original ∈ gap)
    (hShape : SameShape original ((Frame.ofMountain result).cell edge.upper))
    {D : Nat} (hSupported : ∀ w : (Frame.ofMountain result).Node, ∀ i,
      D < i → Row.coeff ((Frame.ofMountain result).height w) i = 0)
    {Label : Type u} [LinearOrder Label] (labels : Fin result.size → Label)
    (hLabels : StrictMono labels) :
    ∃ reference : (Frame.ofMountain result).Node,
      Frame.ref reference =
        ⟨(packet.data.marker_data marker hm).sourceParent.column +
          packet.block * (p.reduced.size - 1 - p.root.column),
          (packet.data.marker_data marker hm).targetIndex⟩ ∧
      (Frame.ofMountain result).cell reference = (packet.data.marker_data marker hm).targetCell ∧
      edge.parent.1 = reference.1 ∧
      (Frame.ofMountain result).height edge.parent < (Frame.ofMountain result).height reference ∧
      edge.degree < Row.jump ((Frame.ofMountain result).height edge.parent)
        ((Frame.ofMountain result).height reference) ∧
      Keys.eval (edge.keyTemplate (expandDiagram_normal hLegal hRun).toOrdered D) labels <
        Keys.truncate (fun i : Fin (D + 1) =>
          labels (scaleRoot (expandDiagram_normal hLegal hRun).toOrdered (D - i.val) reference).1)
          (D + 1) := by
  obtain ⟨reference, middle, hRef, hCell, hColumn, hLow, hHigh, hRung⟩ :=
    packet.reference_gap_edge_rows edge hm hFill hMember hShape
  have hNormal := expandDiagram_normal hLegal hRun
  exact ⟨reference, hRef, hCell, hColumn, hLow.trans_le hHigh,
    edge.degree_lt_reference_jump_of_ladder hNormal.rawRowGeometry hLow hHigh hRung,
    edge.key_lt_reference_of_ladder hNormal hSupported hColumn hLow hHigh hRung labels hLabels⟩

end OmegaY.Expansion

#print axioms OmegaY.Expansion.CopiedNodeOrigin.reference_gap_edge_rows
#print axioms OmegaY.Expansion.CopiedNodeOrigin.reference_gap_edge_key_bound
