/-
Adapted from Phyrion, omega-Y-Well-Ordering-Lean, OmegaY/Expansion/FillRecordPath.lean,
revision 33c16a8ce8f7e01bb3794881f3ff9109474beaed (Apache-2.0).
Changes: none besides this header.
-/
import OmegaY.Expansion.FillCanonical
import OmegaY.Expansion.RawFrontier

/-!
# Finite stored-parent subdivisions generated by actual reference fills

The history below records actual copyColumn executions and eligible parent
intervals. It contains no assumed output adjacency, raw edge, numerical
parent, or path. Each new endpoint is selected from the independently proved
actual fill-interior theorem. Appending such stages gives a finite raw path
to the original source endpoint, and hence subdivides an actual source root
edge. Complete-column preservation keeps that source parent unchanged.

This is a compositional interface for interior fill stages, not a claim that
every block-boundary reference is already represented by such a history.
The final rung/contour seam and arbitrary source-copy stages remain separate.
-/

namespace OmegaY.Expansion

open Canonical Geometry

/-- A real array edge: all three cells are actually read, and the vertical
upper stores the parent's reference. Numerical search is absent. -/
def RawRefEdge (mountain : Mountain) (child parent : Ref) : Prop :=
  ∃ lower upper parentCell, Canonical.cellAt mountain child = .ok lower ∧
    Canonical.cellAt mountain ⟨child.column, child.index + 1⟩ = .ok upper ∧
    upper.left = some parent ∧ Canonical.cellAt mountain parent = .ok parentCell

inductive RawRefPath (mountain : Mountain) : Ref → Ref → Prop
  | refl (ref : Ref) : RawRefPath mountain ref ref
  | cons {child next parent : Ref} (edge : RawRefEdge mountain child next)
      (tail : RawRefPath mountain next parent) : RawRefPath mountain child parent

private theorem upper_of_refs {F : Frame} {u upper : F.Node} {c i : Nat}
    (hu : Frame.ref u = ⟨c, i⟩) (hv : Frame.ref upper = ⟨c, i + 1⟩) :
    F.upper u = some upper := by
  rcases u with ⟨uc, ui⟩
  rcases upper with ⟨vc, vi⟩
  simp only [Frame.ref, Ref.mk.injEq] at hu hv
  have hc : vc = uc := Fin.ext (hv.1.trans hu.1.symm)
  subst vc
  have hNext : ui.val + 1 < F.length uc := by have := vi.isLt; omega
  simp only [Frame.upper, hNext, ↓reduceDIte, Option.some.injEq]
  apply Executable.ref_injective F
  simp only [Frame.ref, Ref.mk.injEq]
  exact ⟨trivial, by omega⟩

theorem RawRefEdge.rawParent {mountain : Mountain} {child parent : Ref}
    (h : RawRefEdge mountain child parent)
    {u p : (Frame.ofMountain mountain).Node}
    (hU : Frame.ref u = child) (hP : Frame.ref p = parent) :
    (Frame.ofMountain mountain).rawParent u = some p := by
  obtain ⟨_, upper, _, _, hUpper, hLeft, _⟩ := h
  obtain ⟨v, hV, hCell⟩ := Canonical.frame_node_of_cellAt hUpper
  have hU' : Frame.ref u = ⟨child.column, child.index⟩ := hU
  apply Frame.rawParent_eq_of_upper_left (upper_of_refs hU' hV)
  simpa only [hCell, hP] using hLeft

theorem RawRefEdge.of_rawParent {mountain : Mountain}
    {u p : (Frame.ofMountain mountain).Node}
    (h : (Frame.ofMountain mountain).rawParent u = some p) :
    RawRefEdge mountain (Frame.ref u) (Frame.ref p) := by
  obtain ⟨upper, hUpper, hLeft⟩ := Frame.rawParent_spec h
  have hRef : Frame.ref upper = ⟨(Frame.ref u).column, (Frame.ref u).index + 1⟩ := by
    simp only [Frame.ref, Ref.mk.injEq]
    exact ⟨congrArg Fin.val (Frame.upper_spec hUpper).1, (Frame.upper_spec hUpper).2⟩
  exact ⟨_, _, _, Canonical.cellAt_of_frame_node mountain u,
    by simpa only [hRef] using Canonical.cellAt_of_frame_node mountain upper,
    hLeft, Canonical.cellAt_of_frame_node mountain p⟩

private theorem preserved_read {before after : Mountain} (h : PreservesColumns before after)
    {ref : Ref} {cell : Cell} (hRead : Canonical.cellAt before ref = .ok cell) :
    Canonical.cellAt after ref = .ok cell := by
  obtain ⟨column, hColumn, _⟩ := Canonical.cellAt_ok_iff.mp hRead
  have hc := (Array.getElem?_eq_some_iff.mp hColumn).1
  exact (cellAt_eq_of_column_eq (h ref.column hc)).trans hRead

theorem RawRefEdge.preserve {before after : Mountain} {child parent : Ref}
    (h : RawRefEdge before child parent) (hColumns : PreservesColumns before after) :
    RawRefEdge after child parent := by
  obtain ⟨lower, upper, parentCell, hLower, hUpper, hLeft, hParent⟩ := h
  exact ⟨lower, upper, parentCell, preserved_read hColumns hLower,
    preserved_read hColumns hUpper, hLeft, preserved_read hColumns hParent⟩

theorem RawRefPath.preserve {before after : Mountain} {child parent : Ref}
    (h : RawRefPath before child parent) (hColumns : PreservesColumns before after) :
    RawRefPath after child parent := by
  induction h with
  | refl _ => exact .refl _
  | cons edge _ ih => exact .cons (edge.preserve hColumns) ih

theorem RawRefPath.trans {mountain : Mountain} {u v w : Ref}
    (h : RawRefPath mountain u v) (tail : RawRefPath mountain v w) :
    RawRefPath mountain u w := by
  induction h with
  | refl _ => exact tail
  | cons edge _ ih => exact .cons edge (ih tail)

/-- Numerical recognition is needed only strictly to the left of a fixed
bound. The current column's P is never a premise. Every target along the
path is recovered from an actual stored-parent read. -/
theorem RawRefPath.toParentPath {mountain : Mountain} (hF : (Frame.ofMountain mountain).Ordered)
    {bound : Nat}
    (hKnown : ∀ node : (Frame.ofMountain mountain).Node, node.1.val < bound →
      Frame.Real node → (Frame.ofMountain mountain).rawParent node = (Frame.ofMountain mountain).P node)
    {child parent : Ref} (h : RawRefPath mountain child parent)
    {u p : (Frame.ofMountain mountain).Node} (hU : Frame.ref u = child)
    (hP : Frame.ref p = parent) (hReal : Frame.Real u) (hLeft : u.1.val < bound) :
    Frame.ParentPath (Frame.ofMountain mountain) u p := by
  induction h generalizing u with
  | refl ref =>
      have he : u = p := Executable.ref_injective _ (hU.trans hP.symm)
      subst u
      exact .refl _
  | @cons child next parent edge tail ih =>
      have edgeCopy := edge
      obtain ⟨_, _, parentCell, _, _, _, hNext⟩ := edgeCopy
      obtain ⟨q, hQRef, _⟩ := Canonical.frame_node_of_cellAt hNext
      have hRaw := edge.rawParent hU hQRef
      have hPQ := (hKnown u hLeft hReal).symm.trans hRaw
      apply Frame.ParentPath.cons hPQ
      exact ih hQRef hP (Frame.real_of_value_pos hF (Frame.P_value hF hPQ).1)
        ((Frame.P_column_lt hF hPQ).trans hLeft)

/-- Inputs for one interior fill stage. The selected output position is not
an input: actual fill and finish determine it in `step` below. -/
structure InteriorFillStage (mountain : Mountain) (previous : Ref) where
  marked : Array (List Ref)
  references : List Ref
  sourceColumn : Nat
  shift : Nat
  rootColumn : Nat
  data : ColumnCopyData mountain marked references sourceColumn shift rootColumn
  output : Column
  run : copyColumn mountain marked references sourceColumn shift rootColumn = .ok output
  parent_power : ∀ marker (hm : marker ∈ data.bucket), ColumnPowerSteps (data.marker_data marker hm).parentNodes
  parent_low : ∀ marker (hm : marker ∈ data.bucket), ∃ (index : Nat) (cell : Cell),
    (data.marker_data marker hm).parentNodes[index]? = some cell ∧
      cell.row = (data.marker_data marker hm).current.row
  no_premature : NoPrematureOne data.sources
  marker : Ref
  marker_mem : marker ∈ data.bucket
  parentIndex : Nat
  degree : Nat
  parent : Cell
  parentUpper : Cell
  parent_at : (data.marker_data marker marker_mem).parentNodes[parentIndex]? = some parent
  parent_upper_at : (data.marker_data marker marker_mem).parentNodes[parentIndex + 1]? = some parentUpper
  eligible : (data.marker_data marker marker_mem).current.row ≤ parent.row ∧
    parent.row < (data.marker_data marker marker_mem).targetCell.row
  interior : degree + 1 < Row.jump parent.row parentUpper.row
  previous_ref : ⟨(data.marker_data marker marker_mem).sourceParent.column + shift, parentIndex⟩ = previous

namespace InteriorFillStage

variable {mountain : Mountain} {previous : Ref} (stage : InteriorFillStage mountain previous)

private theorem relabel_step {mountain : Mountain} {output : Column} {parent : Cell}
    {original target : Ref} {degree : Nat}
    (h : ∃ step : ActualFillStep mountain output original parent,
      SameShape (referenceRung parent.row original.column original.index degree) step.lower ∧
        SameShape (referenceRung parent.row original.column original.index (degree + 1)) step.upper)
    (hRef : original = target) :
    ∃ step : ActualFillStep mountain output target parent,
      SameShape (referenceRung parent.row target.column target.index degree) step.lower ∧
        SameShape (referenceRung parent.row target.column target.index (degree + 1)) step.upper :=
  hRef ▸ h

theorem step_exists : ∃ step : ActualFillStep mountain stage.output previous stage.parent,
    SameShape (referenceRung stage.parent.row previous.column previous.index stage.degree) step.lower ∧
      SameShape (referenceRung stage.parent.row previous.column previous.index (stage.degree + 1)) step.upper := by
  obtain ⟨step, hLower, hUpper⟩ := stage.data.copyColumn_fill_interior
    stage.parent_power stage.parent_low stage.no_premature stage.run stage.marker_mem
    stage.parent_at stage.parent_upper_at stage.eligible stage.interior
  exact relabel_step ⟨step, hLower, hUpper⟩ stage.previous_ref

noncomputable def step : ActualFillStep mountain stage.output previous stage.parent :=
  Classical.choose stage.step_exists

def after : Mountain := mountain.push stage.output

noncomputable def endpoint : Ref := ⟨mountain.size, stage.step.position⟩

theorem endpoint_read : Canonical.cellAt stage.after stage.endpoint = .ok stage.step.lower :=
  Canonical.cellAt_ok_iff.mpr ⟨stage.output, by simp [after, endpoint], stage.step.lower_at⟩

theorem endpoint_row : stage.step.lower.row = Row.bump stage.parent.row stage.degree :=
  (Classical.choose_spec stage.step_exists).1.1.symm

theorem endpoint_real : 0 < stage.endpoint.index := stage.step.position_positive

/-- The new edge is obtained from actual returned adjacency and its stored
left reference; `step.parent_found` is deliberately not used. -/
theorem edge : RawRefEdge stage.after stage.endpoint previous := by
  refine ⟨stage.step.lower, stage.step.upper, stage.parent, stage.endpoint_read, ?_,
    stage.step.upper_left, stage.step.parent_at⟩
  exact Canonical.cellAt_ok_iff.mpr ⟨stage.output, by simp [after, endpoint], stage.step.upper_at⟩

theorem extend_path {root : Ref} (h : RawRefPath mountain previous root) :
    RawRefPath stage.after stage.endpoint root :=
  .cons stage.edge (h.preserve (PreservesColumns.push mountain stage.output))

end InteriorFillStage

/-- A finite sequence of actual fill-interior extensions. The seed is the
original source endpoint; constructors contain only executable input records. -/
inductive FillRecordHistory (source : Mountain) (root : Ref) : Mountain → Ref → Prop
  | seed : FillRecordHistory source root source root
  | extend {mountain : Mountain} {previous : Ref}
      (history : FillRecordHistory source root mountain previous)
      (stage : InteriorFillStage mountain previous) :
      FillRecordHistory source root stage.after stage.endpoint

theorem FillRecordHistory.preservesColumns {source mountain : Mountain} {root endpoint : Ref}
    (history : FillRecordHistory source root mountain endpoint) : PreservesColumns source mountain := by
  induction history with
  | seed => exact fun _ _ => rfl
  | extend _ stage ih => exact ih.trans (PreservesColumns.push _ stage.output)

theorem FillRecordHistory.path {source mountain : Mountain} {root endpoint : Ref}
    (history : FillRecordHistory source root mountain endpoint) : RawRefPath mountain endpoint root := by
  induction history with
  | seed => exact .refl _
  | extend _ stage ih => exact stage.extend_path ih

theorem FillRecordHistory.endpoint_read {source mountain : Mountain} {root endpoint : Ref}
    (history : FillRecordHistory source root mountain endpoint) {rootCell : Cell}
    (hRoot : Canonical.cellAt source root = .ok rootCell) :
    ∃ cell, Canonical.cellAt mountain endpoint = .ok cell := by
  cases history with
  | seed => exact ⟨rootCell, hRoot⟩
  | extend _ stage => exact ⟨stage.step.lower, stage.endpoint_read⟩

theorem FillRecordHistory.endpoint_real {source mountain : Mountain} {root endpoint : Ref}
    (history : FillRecordHistory source root mountain endpoint) (hRoot : 0 < root.index) :
    0 < endpoint.index := by
  cases history with
  | seed => exact hRoot
  | extend _ stage => exact stage.endpoint_real

/-- An actual canonical source root edge becomes a finite stored-parent path
through any finite history of actual fill extensions. The final endpoint is
the original source parent reference, whose complete cell is unchanged. -/
theorem FillRecordHistory.source_parent_subdivision {source mountain : Mountain}
    (hNormal : (Frame.ofMountain source).Normal)
    {root parent : (Frame.ofMountain source).Node}
    (hParent : (Frame.ofMountain source).P root = some parent) {endpoint : Ref}
    (history : FillRecordHistory source (Frame.ref root) mountain endpoint) :
    RawRefPath mountain endpoint (Frame.ref parent) ∧
      Canonical.cellAt mountain (Frame.ref parent) = .ok ((Frame.ofMountain source).cell parent) := by
  have hReal : Frame.Real root := Frame.real_of_value_pos hNormal.toOrdered
    ((Frame.P_value hNormal.toOrdered hParent).1.trans (Frame.P_value hNormal.toOrdered hParent).2)
  have hRaw : (Frame.ofMountain source).rawParent root = some parent :=
    (hNormal.rawParent_eq_P hReal).trans hParent
  have hEdge := (RawRefEdge.of_rawParent hRaw).preserve history.preservesColumns
  exact ⟨history.path.trans (.cons hEdge (.refl _)),
    preserved_read history.preservesColumns (Canonical.cellAt_of_frame_node source parent)⟩

/-- The root edge may be supplied as the actual canonical constructor's
search result. Source normality is obtained from that successful build. -/
theorem FillRecordHistory.build_source_parent_subdivision {input : List Nat}
    {source mountain : Mountain} (hBuild : Canonical.build input = .ok source)
    {root parent : (Frame.ofMountain source).Node}
    (hParent : Canonical.findParent source (Frame.ref root) = .ok (Frame.ref parent))
    {endpoint : Ref} (history : FillRecordHistory source (Frame.ref root) mountain endpoint) :
    RawRefPath mountain endpoint (Frame.ref parent) ∧
      Canonical.cellAt mountain (Frame.ref parent) = .ok ((Frame.ofMountain source).cell parent) :=
  history.source_parent_subdivision (build_normal_of_success hBuild)
    ((Executable.findParent_ref_iff (build_normal_of_success hBuild).toOrdered root parent).mp hParent)

/-- Strict-left recognition turns the constructed subdivision into exactly
the P-path needed to replace one source-root record edge. All intermediate
nodes are recovered from the actual finite fill history. -/
theorem FillRecordHistory.source_parent_records {source mountain : Mountain}
    (hNormal : (Frame.ofMountain source).Normal)
    (hF : (Frame.ofMountain mountain).Ordered) {bound : Nat}
    (hKnown : ∀ node : (Frame.ofMountain mountain).Node, node.1.val < bound →
      Frame.Real node → (Frame.ofMountain mountain).rawParent node = (Frame.ofMountain mountain).P node)
    {root parent : (Frame.ofMountain source).Node}
    (hParent : (Frame.ofMountain source).P root = some parent) {endpoint : Ref}
    (history : FillRecordHistory source (Frame.ref root) mountain endpoint)
    (hBound : endpoint.column < bound) :
    ∃ u p : (Frame.ofMountain mountain).Node, Frame.ref u = endpoint ∧
      Frame.ref p = Frame.ref parent ∧
      (Frame.ofMountain mountain).cell p = (Frame.ofMountain source).cell parent ∧
      Frame.ParentPath (Frame.ofMountain mountain) u p := by
  obtain ⟨hPath, hParentRead⟩ := history.source_parent_subdivision hNormal hParent
  obtain ⟨currentCell, hCurrentRead⟩ := history.endpoint_read (Canonical.cellAt_of_frame_node source root)
  obtain ⟨u, hURef, _⟩ := Canonical.frame_node_of_cellAt hCurrentRead
  obtain ⟨p, hPRef, hPCell⟩ := Canonical.frame_node_of_cellAt hParentRead
  have hRootReal : Frame.Real root := Frame.real_of_value_pos hNormal.toOrdered
    ((Frame.P_value hNormal.toOrdered hParent).1.trans (Frame.P_value hNormal.toOrdered hParent).2)
  have hReal : Frame.Real u := by
    have hIndex := congrArg Ref.index hURef
    have := history.endpoint_real hRootReal
    change u.2.val = endpoint.index at hIndex
    change 0 < u.2.val
    omega
  have hLeft : u.1.val < bound := by
    have hColumn := congrArg Ref.column hURef
    change u.1.val = endpoint.column at hColumn
    omega
  exact ⟨u, p, hURef, hPRef, hPCell, hPath.toParentPath hF hKnown hURef hPRef hReal hLeft⟩

end OmegaY.Expansion

#print axioms OmegaY.Expansion.RawRefEdge.rawParent
#print axioms OmegaY.Expansion.RawRefPath.toParentPath
#print axioms OmegaY.Expansion.InteriorFillStage.edge
#print axioms OmegaY.Expansion.FillRecordHistory.path
#print axioms OmegaY.Expansion.FillRecordHistory.source_parent_subdivision
#print axioms OmegaY.Expansion.FillRecordHistory.build_source_parent_subdivision
#print axioms OmegaY.Expansion.FillRecordHistory.source_parent_records
