/-
Adapted from Phyrion, omega-Y-Well-Ordering-Lean, OmegaY/Expansion/GeneratedWellOrder.lean,
revision 33c16a8ce8f7e01bb3794881f3ff9109474beaed (Apache-2.0).
Changes: none besides this header.
-/
import OmegaY.Expansion.LegalDynamics

/-!
# Conditional well-ordering of actual generated domains

All dynamical hypotheses except accessibility are discharged by the
actual expansion theorems. A single accessible legal starting expression
has a lexicographically well-ordered descendant domain. Well-foundedness
of the actual `Step` on every legal input then gives the well-ordering of
the union generated by the standard seeds `[1,n+2]`.

This file does not prove the remaining `WellFounded Step` hypothesis,
and does not identify the standard generated domain with all syntactically
legal finite sequences.
-/

namespace OmegaY.Expansion.Dynamics

/-- The subtype relation is exactly the successful executable relation;
the choice used to package the total output adds no extra transitions. -/
theorem step_iff_run (child parent : Expr) :
    Step child parent ↔ parent.val ≠ [] ∧
      ∃ copies, expand parent.val copies = .ok child.val := by
  constructor
  · rintro ⟨hn, copies, rfl⟩
    exact ⟨hn, copies, next_run parent copies⟩
  · rintro ⟨hn, copies, hRun⟩
    exact ⟨hn, copies, Subtype.ext (next_eq_of_run hRun)⟩

/-- Accessibility plus the proved nesting of sibling branches makes
any two descendants comparable by actual expansion reachability. -/
theorem endpoints_comparable {root : Expr} (hAcc : Acc Step root) :
    ∀ {a b}, Path root a → Path root b → a = b ∨ Desc a b ∨ Desc b a := by
  induction hAcc with
  | intro s _ ih =>
    intro a b ha hb
    rcases ha.eq_or_first_step with he | ⟨p, hp, hap⟩
    · subst a
      rcases hb.eq_or_desc with he | hb'
      · exact Or.inl he.symm
      · exact Or.inr (Or.inr hb')
    rcases hb.eq_or_first_step with he | ⟨q, hq, hbq⟩
    · subst b
      rcases ha.eq_or_desc with he | ha'
      · exact Or.inl he
      · exact Or.inr (Or.inl ha')
    obtain ⟨i, hi⟩ := hp.2
    obtain ⟨j, hj⟩ := hq.2
    subst p
    subst q
    by_cases hij : i ≤ j
    · exact ih (next s j) hq ((earlier_branch s hij).trans hap) hbq
    · exact ih (next s i) hp hap ((earlier_branch s (by omega : j ≤ i)).trans hbq)

theorem descendants_order_iff {root a b : Expr} (hAcc : Acc Step root)
    (ha : Path root a) (hb : Path root b) : Lex a b ↔ Desc a b := by
  constructor
  · intro hlt
    rcases endpoints_comparable hAcc ha hb with he | hab | hba
    · subst a
      exact (lex_asymm hlt hlt).elim
    · exact hab
    · exact (lex_asymm hlt (desc_lex hba)).elim
  · exact desc_lex

/-- Only accessibility of this particular root is required. -/
theorem descendants_wellFounded {root : Expr} (hAcc : Acc Step root) :
    WellFounded (fun a b : Descendant root => Lex a.val b.val) := by
  refine ⟨fun a => ?_⟩
  apply Subrelation.accessible (r := InvImage Desc (fun s : Descendant root => s.val))
    (fun {x y} h => (descendants_order_iff hAcc x.property y.property).mp h)
  exact InvImage.accessible (fun s : Descendant root => s.val) (a.property.acc hAcc).transGen

theorem descendants_isWellOrder {root : Expr} (hAcc : Acc Step root) :
    IsWellOrder (Descendant root) (fun a b => Lex a.val b.val) where
  wf := descendants_wellFounded hAcc
  trichotomous a b hab hba := by
    rcases lex_trichotomy a.val b.val with h | h | h
    · exact (hab h).elim
    · exact Subtype.ext h
    · exact (hba h).elim

theorem descendants_order_iff_of_wellFounded (hWF : WellFounded Step)
    {root a b : Expr} (ha : Path root a) (hb : Path root b) : Lex a b ↔ Desc a b :=
  descendants_order_iff (hWF.apply root) ha hb

theorem generated_common_root (a b : GeneratedExpr) :
    ∃ n, Path (seed n) a.val ∧ Path (seed n) b.val := by
  obtain ⟨i, hi⟩ := a.property
  obtain ⟨j, hj⟩ := b.property
  exact ⟨max i j, (seed_path i (max i j) (Nat.le_max_left _ _)).trans hi,
    (seed_path j (max i j) (Nat.le_max_right _ _)).trans hj⟩

theorem generated_order_iff (hWF : WellFounded Step) (a b : GeneratedExpr) :
    Lex a.val b.val ↔ Desc a.val b.val := by
  obtain ⟨n, ha, hb⟩ := generated_common_root a b
  exact descendants_order_iff (hWF.apply (seed n)) ha hb

theorem generated_wellFounded (hWF : WellFounded Step) :
    WellFounded (fun a b : GeneratedExpr => Lex a.val b.val) :=
  Subrelation.wf (r := InvImage Desc (fun s : GeneratedExpr => s.val))
    (fun {a b} h => (generated_order_iff hWF a b).mp h)
    (InvImage.wf (fun s : GeneratedExpr => s.val) hWF.transGen)

/-- One-line endpoint for a future proof of actual expansion well-foundedness. -/
theorem generated_isWellOrder (hWF : WellFounded Step) :
    IsWellOrder GeneratedExpr (fun a b => Lex a.val b.val) where
  wf := generated_wellFounded hWF
  trichotomous a b hab hba := by
    rcases lex_trichotomy a.val b.val with h | h | h
    · exact (hab h).elim
    · exact Subtype.ext h
    · exact (hba h).elim

/-- Once actual expansion well-foundedness is known, every legal starting
expression has its own well-ordered descendant domain. This statement
does not order the union of unrelated legal starting expressions. -/
theorem every_legal_root_isWellOrder (hWF : WellFounded Step) (root : Expr) :
    IsWellOrder (Descendant root) (fun a b => Lex a.val b.val) :=
  descendants_isWellOrder (hWF.apply root)

end OmegaY.Expansion.Dynamics

#print axioms OmegaY.Expansion.Dynamics.endpoints_comparable
#print axioms OmegaY.Expansion.Dynamics.step_iff_run
#print axioms OmegaY.Expansion.Dynamics.descendants_order_iff
#print axioms OmegaY.Expansion.Dynamics.descendants_wellFounded
#print axioms OmegaY.Expansion.Dynamics.descendants_isWellOrder
#print axioms OmegaY.Expansion.Dynamics.generated_order_iff
#print axioms OmegaY.Expansion.Dynamics.generated_wellFounded
#print axioms OmegaY.Expansion.Dynamics.generated_isWellOrder
#print axioms OmegaY.Expansion.Dynamics.every_legal_root_isWellOrder
