/-
Adapted from Phyrion, omega-Y-Well-Ordering-Lean, OmegaY/Geometry/FillEdgeKeys.lean,
revision 33c16a8ce8f7e01bb3794881f3ff9109474beaed (Apache-2.0).
Changes: none besides this header.
-/
import OmegaY.Geometry.VerticalEdgeKeys
import OmegaY.Rows.FillLadder

/-!
# Strict key bound for a stored edge generated by a reference ladder

The rung membership gives its actual exponent. The B row law identifies
that exponent with the edge's jump, instead of assuming a degree bound.
Strong vertical growth in the parent column then gives a strict comparison
with the complete (degree-zero) root key of the high reference node.
-/

namespace OmegaY.Geometry.Frame.RealStoredEdge

universe u

theorem degree_eq_of_parent_bump {F : Frame} (e : RealStoredEdge F)
    (hRaw : F.RawRowGeometry) {degree : Nat}
    (hRow : F.height e.upper = Row.bump (F.height e.parent) degree) : e.degree = degree := by
  apply (Row.bump_strictMono_exponent (F.height e.parent)).injective
  calc
    Row.bump (F.height e.parent) e.degree = Row.bump (F.height e.lower) e.degree :=
      (Row.bump_eq_of_jump_le (show Row.jump (F.height e.lower) (F.height e.parent) ≤ e.degree
        from le_rfl)).symm
    _ = F.height e.upper := (e.row_eq hRaw).symm
    _ = Row.bump (F.height e.parent) degree := hRow

/-- An actual rung lies strictly below the high reference in jump scale.
The high endpoint may itself be the rung; its stored left endpoint is still
strictly below the high reference. -/
theorem degree_lt_reference_jump_of_ladder {F : Frame} (e : RealStoredEdge F)
    (hRaw : F.RawRowGeometry) {middle high : Row}
    (hParentMiddle : F.height e.parent < middle) (hMiddleHigh : middle ≤ high)
    (hRung : F.height e.upper ∈ Row.fillLadder (F.height e.parent) middle) :
    e.degree < Row.jump (F.height e.parent) high := by
  obtain ⟨degree, hDegree, hRow⟩ := Row.mem_fillLadder.mp hRung
  have hExact := e.degree_eq_of_parent_bump hRaw hRow.symm
  have hBetween := Row.jump_le_between hParentMiddle.le hMiddleHigh
    (Nat.le_refl (Row.jump (F.height e.parent) high))
  omega

private theorem index_lt_of_same_column_height {F : Frame} (hF : F.Ordered)
    {a b : F.Node} (hc : a.1 = b.1) (hh : F.height a < F.height b) :
    a.2.val < b.2.val := by
  rcases a with ⟨c, i⟩
  rcases b with ⟨d, j⟩
  dsimp only at hc
  subst d
  exact (hF.rows_strict c).lt_iff_lt.mp hh

/-- The entire actual fill key, including its infinity tail, is strictly
below the degree-zero root demand at the high reference endpoint. -/
theorem key_lt_reference_of_ladder {F : Frame} (e : RealStoredEdge F)
    (hNormal : F.Normal) {D : Nat}
    (hSupported : ∀ w : F.Node, ∀ i, D < i → Row.coeff (F.height w) i = 0)
    {reference : F.Node} (hColumn : e.parent.1 = reference.1) {middle : Row}
    (hParentMiddle : F.height e.parent < middle) (hMiddleHigh : middle ≤ F.height reference)
    (hRung : F.height e.upper ∈ Row.fillLadder (F.height e.parent) middle)
    {Label : Type u} [LinearOrder Label] (labels : Fin F.width → Label)
    (hLabels : StrictMono labels) :
    Keys.eval (e.keyTemplate hNormal.toOrdered D) labels <
      Keys.truncate (fun i : Fin (D + 1) =>
        labels (scaleRoot hNormal.toOrdered (D - i.val) reference).1) (D + 1) := by
  have hP : F.P e.lower = some e.parent :=
    (hNormal.rawParent_eq_P e.lower_real).symm.trans e.parent_eq
  have hParentReal := real_of_value_pos hNormal.toOrdered (P_value hNormal.toOrdered hP).1
  have hIndex := index_lt_of_same_column_height hNormal.toOrdered hColumn
    (hParentMiddle.trans_le hMiddleHigh)
  have hDegree := e.degree_lt_reference_jump_of_ladder hNormal.rawRowGeometry
    hParentMiddle hMiddleHigh hRung
  have hV := hNormal.rootVertical hSupported hParentReal hColumn hIndex e.degree hDegree
  rw [e.eval_keyTemplate_eq_truncate hNormal.toOrdered
    (e.degree_le hNormal.rawRowGeometry (hSupported e.upper))]
  exact rootPrefix_lt_arbitrary_truncate hNormal.toOrdered labels hLabels hV _

end OmegaY.Geometry.Frame.RealStoredEdge

#print axioms OmegaY.Geometry.Frame.RealStoredEdge.degree_lt_reference_jump_of_ladder
#print axioms OmegaY.Geometry.Frame.RealStoredEdge.key_lt_reference_of_ladder
